---
# ===============================================================================
# Vault Role Handlers
# ===============================================================================

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart vault
  ansible.builtin.systemd:
    name: vault
    state: restarted
