---
# ===============================================================================
# Role: common
# Description: Common system configuration and package installation
# ===============================================================================

- name: Update package cache (Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Update package cache (RedHat/Rocky)
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Install EPEL repository (RedHat/Rocky/CentOS)
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Ensure /usr/local/bin exists
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Display OS information
  ansible.builtin.debug:
    msg:
      - "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      - "Architecture: {{ ansible_architecture }}"
      - "Kernel: {{ ansible_kernel }}"
