---
# ===============================================================================
# Playbook: DevOps Tools Installation
# Description: Installs Terraform, HashiCorp Vault, and Jenkins on lab VMs
# -------------------------------------------------------------------------------
# Author: rolling (rolling@a-full.com)
# Created: 2025-10-22
# Version: 1.0.0
# ===============================================================================
#
# Usage:
#   # Install all tools
#   ansible-playbook setup_devops_tools.yml
#
#   # Install only Terraform
#   ansible-playbook setup_devops_tools.yml --tags terraform
#
#   # Install Terraform and Vault only
#   ansible-playbook setup_devops_tools.yml --tags terraform,vault
#
#   # Install all except Jenkins
#   ansible-playbook setup_devops_tools.yml --skip-tags jenkins
#
#   # Dry run (check mode)
#   ansible-playbook setup_devops_tools.yml --check
#
# ===============================================================================

- name: Setup DevOps Tools on Lab VM
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Remove existing HashiCorp repository (if present from failed run)
      ansible.builtin.file:
        path: /etc/yum.repos.d/hashicorp.repo
        state: absent
      when: ansible_os_family == "RedHat"
      tags: [always]

  roles:
    - role: common
      tags: [common, always]

    - role: terraform
      tags: [terraform, devops]

    - role: vault
      tags: [vault, devops]

    - role: jenkins
      tags: [jenkins, devops, optional]
      when: install_jenkins | default(false) | bool

  post_tasks:
    - name: Display installation summary
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "✅ DevOps Tools Installation Complete"
          - "=========================================="
          - "Installed tools can be verified with:"
          - "  terraform version"
          - "  vault version"
          - "  systemctl status jenkins  # if installed"
          - "=========================================="
      tags: [always]
